// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	FiatCurrency string
	Genres       string
	Movies       string
	MoviesGenres string
	Users        string
}{
	FiatCurrency: "fiat_currency",
	Genres:       "genres",
	Movies:       "movies",
	MoviesGenres: "movies_genres",
	Users:        "users",
}
